//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace product_manage_task.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_table
    {
        public int order_id { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<int> pid { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
