//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace product_manage_task.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Order_table = new HashSet<Order_table>();
        }
    
        public int pid { get; set; }
        public string pname { get; set; }
        public Nullable<double> price { get; set; }
        public string stock { get; set; }
        public Nullable<int> quantity { get; set; }
        public string photo { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> cust_id_add_card { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_table> Order_table { get; set; }
    }
}
